server:
  port: 7000

spring:
  application:
    name: mall-app-gateway
  cloud:
    nacos:
      discovery:
        register-enabled: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456