server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: admin
  secretKey: 12345678
  bucketName: test