server:
  port: 8082
  servlet:
    context-path: /oms

spring:
  application:
    name: mall-oms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///mall-oms?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456